/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version2;

/**
 *
 * @author FPTDNSB
 */
public class SettingFrame extends javax.swing.JFrame {

    /**
     * Creates new form SettingFrame
     */
    ImageProcessor imageProcessor;
    public SettingFrame(ImageProcessor imageProcessor) {
        initComponents();
        this.imageProcessor = imageProcessor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buGrSetting = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRaBuWhite = new javax.swing.JRadioButton();
        jRaBuBlack = new javax.swing.JRadioButton();
        jRaBuDuplicate = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Border");

        buGrSetting.add(jRaBuWhite);
        jRaBuWhite.setText("White");
        jRaBuWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaBuWhiteActionPerformed(evt);
            }
        });

        buGrSetting.add(jRaBuBlack);
        jRaBuBlack.setText("Black");
        jRaBuBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaBuBlackActionPerformed(evt);
            }
        });

        buGrSetting.add(jRaBuDuplicate);
        jRaBuDuplicate.setSelected(true);
        jRaBuDuplicate.setText("Duplicate");
        jRaBuDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaBuDuplicateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jRaBuWhite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRaBuBlack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRaBuDuplicate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRaBuWhite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRaBuBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRaBuDuplicate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRaBuWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaBuWhiteActionPerformed
        imageProcessor.bufferBordered = imageProcessor.addBorder(imageProcessor.bufferSource, ImageProcessor.TYPE_BORDER.WHITE);
    }//GEN-LAST:event_jRaBuWhiteActionPerformed

    private void jRaBuBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaBuBlackActionPerformed
        imageProcessor.bufferBordered = imageProcessor.addBorder(imageProcessor.bufferSource, ImageProcessor.TYPE_BORDER.BLACK);
    }//GEN-LAST:event_jRaBuBlackActionPerformed

    private void jRaBuDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaBuDuplicateActionPerformed
        imageProcessor.bufferBordered = imageProcessor.addBorder(imageProcessor.bufferSource, ImageProcessor.TYPE_BORDER.DUPLICATE);
    }//GEN-LAST:event_jRaBuDuplicateActionPerformed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buGrSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRaBuBlack;
    private javax.swing.JRadioButton jRaBuDuplicate;
    private javax.swing.JRadioButton jRaBuWhite;
    // End of variables declaration//GEN-END:variables
}
